name: boxe_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  social_share: ^2.1.1   
  shared_preferences: ^2.0.15
  modal_bottom_sheet: ^2.0.0
  http: ^0.13.5
  flutter_native_splash: ^2.2.11
  flutter_launcher_icons: ^0.10.0 
  cupertino_icons: ^1.0.2
  percent_indicator: ^4.2.2
  flutter_lints: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path: "assets/boxe.png"
  android: true 
  ios: true    

flutter_native_splash:
  color: "#F9D87B"
  image: "assets/boxe.png"
  android: true
  ios: true

  flutter_lints: ^1.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/boxe.png
    - assets/chave.png

  fonts:
      - family: Nunito
        fonts : 
        - asset: assets/fonts/Nunito-Regular.ttf
        - asset: assets/fonts/Nunito-SemiBold.ttf
          weight: 500